/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tinyield;

public class App {
    public static void main(String[] args) {
        Sek<Song> songs = Sek.of(
            new Song("505", "Alternative"),
            new Song("Amsterdam", "Alternative"),
            new Song("Mural", "Hip-Hop"));

        Sek<Artist> artists = Sek.of(
            new Artist("Arctic Monkeys", "band"),
            new Artist("Nothing But Thieves", "band"),
            new Artist("Lupe Fiasco", "solo-artist"));

        songs
            .filterNot(song -> song.getName().startsWith("A"))
            .map(Song::getName)
            .zip(artists.distinctBy(Artist::getKind).map(Artist::getName))
            .map(pair -> String.format("%s by %s", pair.getFirst(), pair.getSecond()))
            .forEach(System.out::println);
    }
}
